ci: disable sparse-checkout-cone-mode in action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -53,17 +53,18 @@ runs:
       with:
         fetch-depth: 0
         ref: ${{ inputs.ref }}
+        sparse-checkout-cone-mode: false
 
     - name: Install M-Trust API Guard from Git
       shell: bash
       run: dart pub global activate --source git https://github.com/emdgroup/mtrust-api-guard.git
 
-    # - name: Generate new API docs
-    #   shell: bash
-    #   run: |
-    #     $HOME/.pub-cache/bin/mtrust_api_guard generate \
-    #       --path ${{ inputs.src_path }} \
-    #       --output ${{ inputs.new_doc }} || if [[ "${{ inputs.fail_on_error }}" == "true" ]]; then exit 1; else echo "Ignoring error as fail_on_error is false"; fi
+    - name: Generate new API docs
+      shell: bash
+      run: |
+        $HOME/.pub-cache/bin/mtrust_api_guard generate \
+          --path ${{ inputs.src_path }} \
+          --output ${{ inputs.new_doc }} || if [[ "${{ inputs.fail_on_error }}" == "true" ]]; then exit 1; else echo "Ignoring error as fail_on_error is false"; fi
 
     - name: Run API change type detection
       id: detect_change_type
